FROM athes/swflib:alpine as build-stage

ARG CMAKE_BUILD_TYPE=Release

WORKDIR /src/unpacker
COPY . .

WORKDIR /build/unpacker
RUN apk add --no-cache perl && \
    cmake /src/unpacker && \
    cmake --build . && \
    cmake --install . --strip

FROM alpine:latest as runtime

# Install runtime requirements
RUN apk add --no-cache ca-certificates libstdc++

COPY --from=build-stage /usr/local/bin/unpacker /usr/local/bin/
