FROM athes/swflib:debian-slim as build-stage

ARG CMAKE_BUILD_TYPE=Release

WORKDIR /src/unpacker
COPY . .

WORKDIR /build/unpacker
RUN env && cmake /src/unpacker && \
    cmake --build . && \
    cmake --install . --strip

FROM debian:stable-slim

# Install HTTPS certificates
RUN apt-get update && \
    apt-get install -y --no-install-recommends ca-certificates && \
    rm -rf /var/lib/apt/lists/*

COPY --from=build-stage /usr/local/bin/unpacker /usr/local/bin/
