FROM athes/swflib:alpine as build-stage

ARG CMAKE_BUILD_TYPE=Release
ARG SWFLIB_STATIC=ON

WORKDIR /src/unpacker
COPY . .

WORKDIR /build/unpacker
RUN apk add --no-cache perl && \
    cmake /src/unpacker -DSWFLIB_STATIC=$SWFLIB_STATIC && \
    cmake --build . && \
    cmake --install . --strip

FROM alpine:latest as runtime

# Install runtime requirements
RUN apk add --no-cache ca-certificates libstdc++

COPY --from=build-stage /usr/local/bin/unpacker /usr/local/bin/
